#[build]
#// only build homepage
#command = "webpack" 


[[redirects]]
	from = "/"
	to = "/psa/"
	status = 301
	force = true

[[redirects]]
	from = "/psa/*"
	to = "https://web-psa.netlify.app/psa/:splat"
	status = 200
	force = true

#[[redirects]]
#	from = "/psa/*"
#	to = "https://web-psa.netlify.app/:splat"
#	status = 200
#	force = true

#[[redirects]]
#	from = "/pco/*"
#	to = "https://web-pco.netlify.app/:splat"
#	status = 200
#	force = true
