#[build]
#// only build homepage
#command = "webpack" 

[[redirects]]
	from = "/psa/*"
	to = "https://physicaladdons.netlify.app/psa/:splat"
	status = 200
	force = true

[[redirects]]
	from = "/pco/*"
	to = "https://web-pco.netlify.app/:splat"
	status = 200
	force = true