#[build]
#// only build homepage
#command = "webpack" 


[[redirects]]
	from = "/psa/*"
	to = "https://web-psa.netlify.app/psa/:splat"
	status = 200
	force = true

[[redirects]]
	from = "/blog/*"
	to = "https://pa-blog.netlify.app/:splat"
	status = 200
	force = true

[[redirects]]
	from = "/this-is-a-secret"
	to = "https://web-redirect.netlify.app"
	status = 200
	force = true

	

#[[redirects]]
#	from = "/psa/*"
#	to = "https://web-psa.netlify.app/:splat"
#	status = 200
#	force = true

#[[redirects]]
#	from = "/pco/*"
#	to = "https://web-pco.netlify.app/:splat"
#	status = 200
#	force = true


# Using privacy-first analytics. Do not want to be blocked.
[[redirects]]
	from = "/js/script.js"
	to = "https://plausible.io/js/script.js"
	status = 200
	force = true

[[redirects]]
	from = "/api/event"
	to = "https://plausible.io/api/event"
	status = 200
	force = true