#[build]
#// only build homepage
#command = "webpack" 

[[redirects]]
	from = "/psa/*"
	to = "physicaladdons.netlify.app/:splat"
	status = 200
	force = true

[[redirects]]
	from = "/pco/*"
	to = "pco-addon.netlify.app/:splat"
	status = 200
	force = true